# Generated by Django 5.0.1 on 2024-07-17 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CompanyName", models.CharField(default="", max_length=500)),
                ("Banner", models.CharField(default="", max_length=5000)),
                ("ReadBlogsBanner", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BlogName", models.CharField(default="", max_length=100)),
                ("BlogDescription", models.CharField(default="", max_length=500)),
                ("BlogKeywords", models.CharField(default="", max_length=5000)),
                ("BlogDateAdded", models.CharField(default="", max_length=20)),
                ("BlogImage", models.CharField(default="", max_length=5000)),
                ("BlogSlug", models.CharField(default="", max_length=400)),
                (
                    "BlogCategory",
                    models.CharField(
                        choices=[
                            ("Top Trends", "Top Trends"),
                            ("Failure Chronicles", "Failure Chronicles"),
                            ("Entertainment", "Entertainment"),
                            ("Shark Tank India", "Shark Tank India"),
                            ("Technology", "Technology"),
                            ("Good Reads", "Good Reads"),
                            ("Python", "Python"),
                            ("Business News", "Business News"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("BlogPost", models.TextField(default="", max_length=10000)),
                ("BlogAuthor", models.CharField(default="", max_length=50)),
                ("Views", models.CharField(default="0", max_length=50)),
                (
                    "Likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserLikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="", max_length=200)),
                ("Email", models.EmailField(default="", max_length=200)),
                ("Comment", models.TextField(default="", max_length=1000)),
                (
                    "Date",
                    models.CharField(
                        default="2024-07-17 21:24:58.263768", max_length=40
                    ),
                ),
                ("ActualDate", models.CharField(default="17-07-2024", max_length=40)),
                ("User_ProfilePhoto", models.CharField(default="", max_length=200)),
                (
                    "BlogDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BlogDet",
                        to="ArticlesWebsite.blog",
                    ),
                ),
                (
                    "UserDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CommentsUserDet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForgottenPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OTP", models.CharField(default="", max_length=20)),
                (
                    "UserDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OTPforpasswordrecovery",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Photo",
                    models.ImageField(
                        default="static/Images/User%20profile.png",
                        upload_to="UserProfilePhoto",
                    ),
                ),
                (
                    "UserDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserPhoto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
