# Generated by Django 5.0.1 on 2024-07-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArticlesWebsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2024-07-17 21:30:32.093720", max_length=40),
        ),
    ]
